apache/infrastructure-website

- content/pages/committers.md
The link was not formatted correctly and thus could not be displayed correctly.
This PR fixes the markdown formatting.
> fix markdown formatting for link

- content/pages/committers.md
The link was not formatted correctly and thus could not be displayed correctly.
This PR fixes the HTML.
> fix HTML link

- content/pages/licensing-howto.md
I just checked the [Notice file of Apache Royale](https://github.com/apache/royale-asjs/blob/develop/NOTICE),  it doesn't have copyright information of Github.
> Removed the  copyright of Github from Notice

- content/pages/version-control.md
the indentation already makes sure it's treated as a code block
> remove redundant backticks

- content/pages/mailing-list-moderation.md
Remove the unneeded paragraph tags. The following section doesn't display the markdown characters correctly: https://infra.apache.org/mailing-list-moderation.html#mailing-list-moderators
I think this has to do because of the mixing of HTML and markdown on the same line. Since I see no real use case for inserting a `<p>` tag, just remove it.
I also removed the rogue `</p>` closing tag, which doesn't have a matching opening tag.
I tried testing this locally using the instructions in the README, but that didn't work for me, see the log:
```bash
[rlenferink@fedora infrastructure-website]$ virtualenv venv
created virtual environment CPython3.11.1.final.0-64 in 111ms
creator CPython3Posix(dest=/home/rlenferink/workspace/asf/infra/infrastructure-website/venv, clear=False, no_vcs_ignore=False, …
```
> Remove unneeded paragraph tags

- content/pages/digicert-use.md
Hi,
Web documentation changed in digicert. I think the new url is containing the documentation to set the variable.
Signtools.exe is missing the /td option now. Was not the case previously
> fix documentation url and signtool command

- content/pages/release-signing.md
Trivial thing. When reading the web document, I just noticed that a space was missing in a command.
> Add missing space in command on release signing page

- content/pages/digicert-use.md
To avoir deprecated certification after certification is no more valid it's better to add this argument.
This will be more consistent with other example (ant, and signtool)
> make explicit the tsaurl argument is jsign example

- content/pages/infra-contact.md
-provided complete address for littleblackbook.txt
-removed a paragraph of limited use about contacting an Infra member via SMS
> Cottage14 patch 2 improvements to 'emergency-contact' information

- content/pages/team.md
Fixes : #139 
- for help , user should navigate to the contact page to contact the team for any help same as the homepage as below
[apache-homepage.webm](https://github.com/apache/infrastructure-website/assets/107138786/37ccd361-7192-4921-991a-c41c5a616b95)
- thus, I added link to contact page so that user can contact the team if they want any help from them
> added an accurate navigation link for [help] in the team page

- content/pages/infra-contact.md
Fixes: #143 
Added the Exact Link of the Services and tools page same as given in homepage of the website as shown below
[issue_solved.webm](https://github.com/apache/infrastructure-website/assets/107138786/18a62124-b3a9-4913-a9e5-9e49f247ac2f)
> Added exact Link of the Services and tools page

- content/pages/infra-contact.md
Fixes: #145 
I added the expected link on the [self serve] anchor same as given in [self serve] anchor of  {svn-to-git-migration} page as shown below
[issue_solved.webm](https://github.com/apache/infrastructure-website/assets/107138786/47a409d5-4a4a-4689-b6f3-9d5070348375)
> Added exact link to be navigated after clicking the [self serve] anchor in the infra-contact page of svn to git migration block

- content/pages/infra-contact.md
Fixes: #147 
Added the exact link of the page for creating jira project instead of given invalid link to render same as expected behavior as given below
[expected_behavior.webm](https://github.com/apache/infrastructure-website/assets/107138786/0469afed-452b-4105-8808-adf7cd93ba58)
> added the correct link for creating jira project to render

- content/pages/infra-contact.md
Fixes : #149 
I added the link to create confluence wiki space in place of the previous given link so that it should render to the expected page as below shown 
[Uploading expected_behavior.webm…]()
> added correct link for creating confluence wiki space to render

- content/pages/patch.md
Fixes : [ #153 ]
**Changes**
I Removed Invalid Link from the subversion basics of [patch page] and added the expected link in it's place which will redirect to the subversion basics page as shown below
> Removed Invalid Link from the subversion basics and added the expected link which will redirect to the subversion basics page

- content/pages/github-actions-secrets.md
example for extending the validity of a Develocity short-lived token.
> Update github-actions-secrets.md added example per issue 198

- content/pages/slack.md
This distinction is not so visible in the UI anymore, and while multi-channel guests are still mentioned in https://slack.com/help/articles/201314026-Permissions-on-a-Slack-workspace AFAICS neither can join channels they're not invited to (anymore?).
Happy to take feedback if I misunderstood
> slack: diminuish distinction between single- and multi-channel guests

- content/pages/bug-writing-guide.md
The existing BZ link points to a single instance, which does not include all projects using BZ.
Whereas the Jira link points to the sole instance.
> Point to BZ listing of instances

- content/pages/asf-pelican-config.md
The colon was on the wrong side of the slashes
> Fix typo in href

- content/pages/asf-pelican-branches.md
- content/pages/asf-pelican-build.md
- content/pages/asf-pelican-data.md
- content/pages/asf-pelican-gettingstarted.md
- content/pages/asf-pelican-plugins.md
- content/pages/asf-pelican-theme.md
- content/pages/website-guidelines.md
Seems like a copy and paste error, where the colon was placed on the wrong side of the slashes.
> Fix typo in URL
